[shell]
program = "/bin/zsh"
args = ["-l"]

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[font]
size = 11.0

[window] 
decorations = "None"
opacity = 0.7
startup_mode = "Fullscreen"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

# [schemes.tokyo-night.bright]
# black = "0x444b6a"
# blue = "0x7da6ff"
# cyan = "0x0db9d7"
# green = "0xb9f27c"
# magenta = "0xbb9af7"
# red = "0xff7a93"
